### ISSUE TITLE
Upload file with cyrillic return 400 error 

### ISSUE THREAD

**Issue by alexandrhotko** [OneDrive/onedrive-sdk-ios#102]
I try to upload files throught call:
`[ [ [ [ client root ] itemByPath:@"Д.jpg" ] contentRequest ] uploadFromFile:[ NSURL fileURLWithPath:from ] completion:^(ODItem * item, NSError * error) { NSLog(@"%@", error); } ];`

When I try upload new file with name "Д.jpg", it return 400 error. Error disappears, if I change name to "Ф.jpg" or any other.

Strange problem. I use cocoapods.

**Comment by kevklam** [comment]
There is a known unicode bug on service side that returns this error. The bug has been fixed and will be deploying sometime in the next few weeks.

However, I was unable to reproduce your specific issue (see screenshot) even though the fix should not be deployed yet.

<img width="633" alt="screenshot 2016-05-31 17 35 16" src="https://cloud.githubusercontent.com/assets/16890026/15694851/15a3e768-2756-11e6-8a7c-4125e96cfb80.png">

If this is a time sensitive issue, can you provide an HTTP trace of the request via Charles or similar web debugging proxy? Otherwise, it may be worthwhile to wait for the service side fix to deploy and see if the problem is resolved.

**Comment by alexandrhotko** [comment]
The problem was reproduced within a week, but now it's gone. Error 400 doesn't appear.

**Comment by kevklam** [comment]
Considering this as not reproducible - please reopen this issue if the problem comes back.

Thanks!
