### ISSUE TITLE
Delay between dismissing auth VC and invoking completion

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#108]
For example login code: completion block is executed after dismissViewController. Actual result - broken UI. In my case `-[UITableView reloadData]` causes random bugs in table

**Comment by kevklam** [comment]
Please clarify what issue you are having. Are you seeing a bug, or are you just dissatisfied with how asynchronous callbacks work?

**Comment by gerchicov-bp** [comment]
In my case I want to call `reloadData` in the completion block. If I use your code then it seems delegate methods `numberOfSections` and `numberOfRowsInSection:` are called normally. But `cellForRowAtIndexPath` is called with a huge delay. The only reason I see is I try to reload table at the same time you want to dismiss view controller.

And the only solution I see is to fix `authorizationFlowCompletedWithURL:error:presentingViewController:completion:` - I execute `completionHandler` then `dispatch_async` with `dismissViewControllerAnimated:completion:`. In your case when you call branch with `[self getTokenWithCode:code completion:completionHandler];` this order is fractured.

**Comment by kevklam** [comment]
To clarify - the 'broken UI' that you mention is that there is a long delay between dismissing the webview and invoking the completion block? If I am understanding correctly, you're right - this is not a great user experience. However, the completion block must not be invoked before getTokenWithCode completes because the client will have nil accountSession and requests will fail with an error.

There are several possible options to address this - broadly bucketed into "delay dismissing VC until getTokenWithCode completes", or "dismiss immediately and invoke an extra vc-did-dismiss callback immediately before client is setup".

I'll try to get to this sometime this week or the next, or if this is blocking you please feel free to create a fork and make your own modifications temporarily.

**Comment by gerchicov-bp** [comment]
In both cases it requires to edit/override inner library methods. And it looks like a bug because it may break any UI elements appearance and animation.
