### ISSUE TITLE
Chunked Upload Support

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#122]
I created a temp file (creates file of size 107Mb):
`mkfile -n 107m 1.rar`

I try to upload it and it works but in the completion block I always get a random error. Examples of errors:
`...2.rar, error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

`OneDrive SDK ERROR : Error from download response Error Domain=com.microsoft.onedrive.errors Code=413 "request too large" UserInfo={NSLocalizedDescription=request too large}`

**Comment by gerchicov-bp** [comment]
json parser can't parse response from microsoft because ... it is html?!

`<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: 717034FBB0C14AA9B185B9AD9693D11B Ref B: CC6DA74E47ED1A4FF072E6E72E854065 Ref C: Tue Jun 21 08:03:25 2016 PST</span></div></div></body></html>`

**Comment by gerchicov-bp** [comment]
finally I have found the following on the official websiite:
https://dev.onedrive.com/items/upload_put.htm

> The simple upload API allows you to provide the contents of a new file or update the contents of an existing file in a single API call. This method only supports files up to 100MB in size. For larger files use resumable upload.

As I understand you use this "simple upload" method. And other types are not implemented, aren't they?

**Comment by pedro-bread** [comment]
Would love to see progress on this as well. Any ETA on the horizon?

**Comment by tobihagemann** [comment]
I'm trying to implement chunked uploading at the moment as well. It looks like it's called "creating an upload session" and then "upload fragments": https://dev.onedrive.com/items/upload_large_files.htm

I found some code in this SDK to create an upload session, even though it's not documented anywhere and not used in the example project.

This is how far I've got:

``` objc
ODClient *client = ...;

// create an upload session: https://dev.onedrive.com/items/upload_large_files.htm#create-an-upload-session
ODChunkedUploadSessionDescriptor *item = [[ODChunkedUploadSessionDescriptor alloc] init];
item.name = @"largefile.dat"; // not sure, but it looks like you have to fill in the filename
ODURLSessionDataTask *task = [[[[client root] createSessionWithItem:item] request] executeWithCompletion:^(ODUploadSession *response, NSError *error) {
    // upload fragment: https://dev.onedrive.com/items/upload_large_files.htm#upload-fragments
}];
```

It's a simple example on creating a chunked upload session in a user's root folder of their drive. But you can obviously create an `ODItemRequestBuilder` instance for your needs (e.g. by ID with `items:` or by path with `itemByPath:`).

The `response` object should contain the `uploadUrl` that can be used to upload the fragment(s). This is the point, where I think that the SDK doesn't offer any high level API to do exactly that, because there is no hint of a request builder that also sets the `Content-Length` and `Content-Range` headers accordingly. It looks like we have to build an `NSMutableURLRequest` the old-fashioned way. After that we still can use `ODURLSessionUploadTask` to upload the fragment though.

I'm not particularly amused about this lower level implementation, but at least it's not a dead-end. :wink:

**Comment by pedro-bread** [comment]
Thanks tobihagemann. That helped a lot.

**Comment by nouatzi** [comment]
Hi, I'm having issue with resumable upload too.
My approach is a bit different. Instead of using onedrive SDK, I implement it with URLSession in iOS.
Everything works, except the resumable upload. 
The session upload creation works, I've got my uploadUrl, so I simply start an URLSessionUploadTask:

```
let url = URL(string: urlUploadString)!
var urlRequest = URLRequest(url: url)
urlRequest.httpMethod = "PUT"
urlRequest.setValue("bearer \(accessToken)", forHTTPHeaderField: "Authorisation")
let task = urlsession.uploadTask(with: urlRequest, from: data)
task.resume()
```

The transfer goes through, however, in the end, I receive a http code 400 with the response:

```
["error": {
    code = invalidRequest;
    message = "Invalid Content-Range header value";
}]
```

The thing, I can't set the Content-Range header per packet, because iOS handles the upload, not me. And it doesn't seem to set Content-Range header automatically for each chunk sent.

**Comment by tobihagemann** [comment]
Yes, you can set the HTTP headers yourself. This is what my request builder looks like for chunked upload:

``` objc
- (void)buildRequestForFileChunkUploadWithURL:(NSURL *)url chunkLength:(NSUInteger)chunkLength offset:(NSUInteger)offset totalLength:(NSUInteger)totalLength callback:(void (^)(NSMutableURLRequest *request, NSError *error))callback {
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringLocalCacheData timeoutInterval:60.0];
    request.HTTPMethod = @"PUT";
    NSString *contentLength = [NSString stringWithFormat:@"%tu", chunkLength];
    [request addValue:contentLength forHTTPHeaderField:@"Content-Length"];
    NSString *contentRange = [NSString stringWithFormat:@"bytes %tu-%tu/%tu", offset, offset + chunkLength - 1, totalLength];
    [request addValue:contentRange forHTTPHeaderField:@"Content-Range"];
    [self.client.authProvider appendAuthHeaders:request completion:callback];
}
```

Notice also my last line, so that you don't have to add the bearer token yourself.

**Comment by nouatzi** [comment]
But you call this method once, to build your request. How did the Content-Range value get updated every time iOS upload a file fragment ?
Did iOS will automatically add and increment the Content-Range value for all fragments sent ?

**Comment by tobihagemann** [comment]
Nope, there is nothing automatic about it. You have to do it manually and follow the protocol as I've linked before: https://dev.onedrive.com/items/upload_large_files.htm

> When the request is complete, the server will respond with HTTP 202 Accepted if there are more fragments of the file that need to be uploaded.
> ...
> When the last fragment is received and the server has all of the file's bytes, the server will respond with HTTP 201 Created (for a new file) or HTTP 200 OK for an updated file and include an Item resource for the uploaded file

You have to determine yourself how big your file chunk is (best practices are noted at the bottom). For example, I've chosen `5 * 1024 * 1024`.

> Use a fragment size that is a multiple of 320 KiB (320 \* 1024 bytes). Failing to use a fragment size that is a multiple of 320 KiB can result in large file transfers failing after the last fragment is uploaded.

Basically, if you've successfully uploaded a file chunk, you have to upload the next file chunk (e.g. you can do that recursively and increment the offset with each step).

**Comment by nouatzi** [comment]
Yes I know OneDrive has a protocol to upload file.
So if I understand right, you're creating a NSURLSessionUploadTask for EACH chunk to send. 
Or, you're sending your file manually, for instance with NSStream.

**Comment by tobihagemann** [comment]
> So if I understand right, you're creating a NSURLSessionUploadTask for EACH chunk to send. 

Correct. I must admit that I was a little lazy and I'm using `AFNetworking` on top of `NSURLSessionUploadTask` with `[[AFHTTPSessionManager manager] uploadTaskWithRequest:fromData:progress:completionHandler:]]`, because I prefer block-based solutions instead of delegates. I've been using this library in my project anyway. But that's basically the solution: Create an upload task for each chunk and send them sequentially.

**Comment by nouatzi** [comment]
Ooooooooook, now I understand. Yes it's really weird to do that, but I've tried it and it worked, so 👍 .
Thank you very much tobihagemann for helping me !!
