### ISSUE TITLE
Continuous reauthentication

### ISSUE THREAD

**Issue by sameerKLT** [OneDrive/onedrive-sdk-ios#140]
Im authenticating and uploading files to onedrive like so:

```
[ODClient clientWithCompletion:^(ODClient *client, NSError *error){
       if (!error){
           [[ODAccountStore defaultAccountStore] storeCurrentAccount:[client.authProvider          accountSession]];
          self.oneDriveClient = client;
          [self uploadToOneDriveWithURL:self.urlRequest.mainDocumentURL];
      }
      else if (error && [error isAuthenticationError]){
         NSLog(@"%@"error.localizedDescription);
      }
}];
```

This allows me to go through and returns no error if I have logged in once before. But once I start uploading to OneDrive with the `ODURLSessionUploadTask` I get a 401 unauthorized and I have to force the user to reauthenticate. 

Is there something here that I am doing wrong? When the user is navigated back to the authentication page, OneDrive only asks for access to their account and not user login.

**Comment by kevklam** [comment]
Are you specifying the 'offline_access' scope when setting up the appID/scopes? Doing so will make the SDK receive an OAuth refresh token from the auth flow, allowing the SDK to automatically refresh the access token when it expires every hour.

On navigating back to the authentication page, it bypasses the login due to the iOs browser component caching some auth related cookies to keep the user signed in (this is different from the token used to authenticate the API requests made by the SDK, which expires every hour).

**Comment by KeylimeGit** [comment]
Works great! 

Thank you!

**Comment by sameerKLT** [comment]
Works Great!

Thank you
