### ISSUE TITLE
Sign out when no internet connection

### ISSUE THREAD

**Issue by JustStoryteller** [OneDrive/onedrive-sdk-ios#169]
I try to sign out OneDrive account when no internet connection, using [currentClient signOutWithCompletion:^(NSError *error){}]. Then I try to sign in to other account, using [ODClient authenticatedClientWithCompletion:^(ODClient *client, NSError *error){}] - and, when I call this method, 'confirm permissions' view controller appears instead of 'enter login and password' view controller. So, I can't sign in to other account. 
If internet connection available - it's OK.

**Comment by kevklam** [comment]
This is because the signout flow makes a request to a URL which clears the auth related cookies.  If there is no connection, the sign-out URL is not reachable and the cookies are not cleared.

You should be able to tell if sign-out was successful by checking if the NSError passed to the completion block is nil or not. In the case that there was an error reaching the endpoint, one possible workaround is to clear all cookies - this will sign the user out, however has the undesirable side effect of also signing out of any other cloud services that might have had cookies stored. If your app does not use other cloud services, this may not be an issue.

Ideally we would selectively clear the relevant cookies without needing to make the request to the sign-out endpoint, however the auth flows and cookies are continually changing and any logic attempting to target specific cookies would likely break periodically.
