### ISSUE TITLE
duplicate symbol problem

### ISSUE THREAD

**Issue by tigernghk** [OneDrive/onedrive-sdk-ios#23]
I have followed the instruction to install pods. One question: Add the following to your Podfile : pod 'OneDriveSDK' => it means append pod 'OneDriveSDK' to the line of the file ?

When I open OneDriveSDK.xcodeproj and start build, it shows the following errors:

duplicate symbol _OBJC_CLASS_$_ODAADAccountBridge in:
    /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/OneDriveSDK-acgkcrgmhevkjlgmfsreytxbrcqw/Build/Intermediates/OneDriveSDK.build/Debug-iphoneos/OneDriveSDK.build/Objects-normal/arm64/ODAADAccountBridge.o
    /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/OneDriveSDK-acgkcrgmhevkjlgmfsreytxbrcqw/Build/Products/Debug-iphoneos/libOneDriveSDK.a(ODAADAccountBridge.o)
duplicate symbol _OBJC_METACLASS_$_ODAADAccountBridge in:
    /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/OneDriveSDK-acgkcrgmhevkjlgmfsreytxbrcqw/Build/Intermediates/OneDriveSDK.build/Debug-iphoneos/OneDriveSDK.build/Objects-normal/arm64/ODAADAccountBridge.o
    /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/OneDriveSDK-acgkcrgmhevkjlgmfsreytxbrcqw/Build/Products/Debug-iphoneos/libOneDriveSDK.a(ODAADAccountBridge.o)
duplicate symbol _OBJC_CLASS_$_ODAADServiceInfo in:
    /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/OneDriveSDK-acgkcrgmhevkjlgmfsreytxbrcqw/Build/Intermediates/OneDriveSDK.build/Debug-iphoneos/OneDriveSDK.build/Objects-normal/arm64/ODAADServiceInfo.o
    /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/OneDriveSDK-acgkcrgmhevkjlgmfsreytxbrcqw/Build/Products/Debug-iphoneos/libOneDriveSDK.a(ODAADServiceInfo.o)

ld: 400 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I cannot compile the project.

**Comment by aclev** [comment]
Hi @tigernghk 
If you are adding the SDK to your own project you will need to follow the cocoapods getting started [guide](http://guides.cocoapods.org/using/getting-started.html).  In your own Podfile you must add `'Pod OneDriveSDK'` under your target section of your Podfile.  If you had an xcode project name "Foo" it would look like this :

```
target 'Foo' do
    pod 'OneDriveSDK'
end
```

After this you must run a `pod install`, cocoapods will then tell you to close the .xcproj and you must use the .xcworkspace it created for you instead of the .xcproj file.  Once you have opened the xcworkspace in xcode you shouldn't ever need to open the actual OneDriveSDK project and only include `#include <OneDriveSDK/OneDriveSDK.h>` in the files that use the SDK.
Thanks!
