### ISSUE TITLE
Search API Query parameter doesn't have OR operator ?

### ISSUE THREAD

**Issue by pavanSaberjack** [OneDrive/onedrive-sdk-ios#77]
I was using Search API to fetch files. I wanted fetch specific type of files and get children API is time consuming and I have to recursively crawl through the folders.

Anything I can use to query such as  **query = 'abc OR xyz'** which would return me filename, metadata, and file content having **'abc'** or **'xyz'**. As I currently this is not possible for now.

Thanks

**Comment by kevklam** [comment]
Hi @pavanSaberjack,
My apologies for the slow reply. Has your issue been resolved yet? My suggestion would be to try query='abc xyz' as this seems to have roughly the semantics you are looking for. 

Due to #78, if you are using a commit prior to "06b51e2e90336fcc946f440cd58af5e84920a260", the query param would need to be encoded as "abc+xyz" or "abc%20xyz", or if you point your podfile at this commit or later simply "abc xyz".

**Comment by kevklam** [comment]
Closing issue for now - please reopen if this needs further attention.

**Comment by pavanSaberjack** [comment]
@kevklam I tried setting query as 'abc%20xyz' and 'abc+xyz' and results are wrong. When I just tried query as 'abc' it gave more results than when i used 'abc%20xyz' OR 'abc+xyz'
Still not working as expected for me

**Comment by kevklam** [comment]
@pavanSaberjack - Unfortunately it looks like there is no way currently to explicitly specify OR semantics.

According to the Search team, the semantics are as follows:
1. Use AND semantics on all search terms
2. If no search results are found, it reduces the number of search terms required to be matched by [relaxCount], which is currently defined to be 1, and re-searches.

I am still actively engaged with them and we are attempting to determine if it's feasible to expose finer grained control of search parameters in the API, however there is nothing currently on the roadmap.

For the time being, the Search API should not be relied upon for specific semantics beyond "give me files that may be interesting based on these search terms".

Thanks,
Kevin
